# Use cargo-make to run tasks here: https://crates.io/crates/cargo-make

[tasks.format]
description = "Formats the code using unstable features for better import grouping"
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Crate,group_imports=StdExternalCrate,reorder_imports=true,format_code_in_doc_comments=true",
]

[tasks.check]
description = "Quickly check if the relay compiles"
command = "cargo"
args = ["check", "-p", "relay", "--features", "server"]

[tasks.build-relay]
description = "Build the relay binary in release mode"
command = "cargo"
args = ["build", "--release", "-p", "relay", "--features", "server"]

[tasks.run-relay]
description = "Run the relay in dev mode"
command = "cargo"
args = ["run", "-p", "relay", "--features", "server", "--", "--dev"]

