# Base build image for Rust on Alpine
FROM rust:alpine AS chef

RUN update-ca-certificates
RUN apk add --no-cache musl-dev openssl-dev pkgconfig
RUN cargo install cargo-chef
WORKDIR /acerola

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

### Builder image
FROM chef AS rust_builder

RUN update-ca-certificates
RUN apk add --no-cache musl-dev openssl-dev pkgconfig

COPY --from=planner /acerola/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

WORKDIR /acerola

# copy entire workspace
COPY . .

# Build the relay binary specifically
RUN cargo build --release --bin relay --features server

### Target image
FROM alpine:latest AS acerola-relay

RUN apk update && apk add ca-certificates && update-ca-certificates

# Copy our build from the builder stage
COPY --from=rust_builder /acerola/target/release/relay /relay

RUN chmod +x /relay

WORKDIR /

# expose the default ports
# 80/443 for HTTP/HTTPS/Websockets
# 7824/udp for QUIC Address Discovery
# 9090 for Metrics
EXPOSE 80 443 7824/udp 9090

ENTRYPOINT ["/relay"]
CMD [""]
