services:
  relay:
    build:
      context: ../..
      dockerfile: .config/docker/dockerfile
    container_name: acerola-relay
    restart: always
    environment:
      - IROH_RELAY_HTTP_BEARER_TOKEN=${RELAY_TOKEN:-}
    ports:
      - "7824:7824/udp"
    networks:
      - acerola-net
    volumes:
      - ./certs:/certs
    command: ["--config-path", "/config.toml"]

  caddy:
    image: caddy:latest
    container_name: acerola-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - acerola-net
    depends_on:
      - relay

networks:
  acerola-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
        - subnet: fd00:ace:1010::/64
