[relay_servers]
# Adicione o IP ou hostname do seu servidor aqui
# exemplo: 192.168.1.100 ansible_user=rocky acerola_email=voce@exemplo.com acerola_domain=relay.exemplo.com relay_token=seu_token_secreto
192.168.0.1 ansible_user=root ansible_ssh_forward_agent=true email=contato@exemplo.com domain=acerola.exemplo.com